#  Tags are assigned to the corresponding resources being created.
#    "application" represents team name, e.g. 'probate', 'divorce', use 'core' for platform infrastructure.
#    "businessArea" represents the business area this application belongs to, one of CFT / Crime / Cross-Cutting.
#  Further docs: https://tools.hmcts.net/confluence/display/DCO/Tagging+v0.4

sds-platform:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

cft-platform:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "CFT"

soc:
  team: "soc"
  namespace: ""
  slack:
    contact_channel: "#sec-ops"
    build_notices_channel: ""
  tags:
    application: "security"
    businessArea: "Cross-Cutting"

ethos:
  team: "ethos"
  namespace: ""
  slack:
    contact_channel: "#ethos-repl-service"
    build_notices_channel: ""
  tags:
    application: "ethos"
    businessArea: "Cross-Cutting"

heritage:
  team: "heritage"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "heritage"
    businessArea: "Cross-Cutting"

mi:
  team: "mi"
  namespace: ""
  slack:
    contact_channel: "#mi-data-platform"
    build_notices_channel: ""
  tags:
    application: "management-information"
    businessArea: "Cross-Cutting"

pet:
  team: "pet"
  namespace: ""
  slack:
    contact_channel: "#pet-devops"
    build_notices_channel: ""
  tags:
    application: "pet"
    businessArea: "Cross-Cutting"

robotics:
  team: "robotics"
  namespace: ""
  slack:
    contact_channel: "#robotics"
    build_notices_channel: ""
  tags:
    application: "robotics"
    businessArea: "Cross-Cutting"

mgmt:
  team: "mgmt"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: ""
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

hub:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

sds-jenkins:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

mailrelay:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"
hmi:
  team: "hmi"
  namespace: ""
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: ""
  tags:
    application: "hearings-management-interface"
    businessArea: "Cross-Cutting"
toffee:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"
netbox:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"
juror-digital:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "juror-digital"
    businessArea: "Cross-Cutting"
ctsc:
  team: "CTSC"
  namespace: "ctsc"
  slack:
    contact_channel: "#ctsc-master-builds"
    build_notices_channel: "#ctsc-master-builds"
  tags:
    application: 'courts-tribunals-service-centre'
    businessArea: "Cross-Cutting"
vh:
  team: "Video Hearings"
  namespace: "vh"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: 'video-hearings-service'
    businessArea: "Cross-Cutting"
wowza:
  team: "Video Hearings"
  namespace: "vh"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: 'video-hearings-service'
    businessArea: "Cross-Cutting"
pip:
  team: "Publishing and Information"
  namespace: "pip"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: 'publishing-information-service'
    businessArea: "Cross-Cutting"
cvp:
  team: "Cloud Video Platform"
  namespace: "cvp"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: 'cloud-video-platform'
    businessArea: "Cross-Cutting"
shared-image-gallery:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: 'core'
    businessArea: "Cross-Cutting"

caps:
  team: "caps"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "caps"
    businessArea: "Cross-Cutting"

pcol:
  team: "pcol"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "pcol"
    businessArea: "Cross-Cutting"

caseman:
  team: "caseman"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "caseman"
    businessArea: "Cross-Cutting"

mcol:
  team: "mcol"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "mcol"
    businessArea: "Cross-Cutting"

bais:
  team: "bais"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "bais"
    businessArea: "Cross-Cutting"

darts-idam:
  team: "darts-idam"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "darts-idam"
    businessArea: "Cross-Cutting"

sdt:
  team: "sdt"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "heritage-secure-data-transfer"
    businessArea: "Cross-Cutting"

application-performance-management:
  team: "apm"
  namespace: "dynatrace"
  slack:
    contact_channel: "dynatrace-help-admins"
    build_notices_channel: ""
  tags:
    application: "application-performance-management"
    businessArea: "Cross-Cutting"

template-management:
  team: "template-management"
  namespace: "docmosis"
  slack:
    contact_channel: "docmosis"
    build_notices_channel: "docmosis-builds"
  tags:
    application: "template-management"
    businessArea: "CFT"