sds-platform:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cost-Cutting"