#  Tags are assigned to the corresponding resources being created.
#    "application" represents team name, e.g. 'probate', 'divorce', use 'core' for platform infrastructure.
#    "businessArea" represents the business area this application belongs to, one of CFT / Crime / Cross-Cutting.

sds-platform:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

cft-platform:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "CFT"

soc:
  team: "soc"
  namespace: ""
  slack:
    contact_channel: "#sec-ops"
    build_notices_channel: ""
  tags:
    application: "core"
    businessArea: "Cross-Cutting"        

sdsacme:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

cftacme:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "CFT"
